django/g2c/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^g2c/', include('g2c.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
    (r'^test/'       , 'g2c.converter.views.test' ),
    (r'^api/convert' , 'g2c.converter.views.convert' ),
)

django/g2c/converter/models.py
from django.db import models
from django    import forms


class ConverterForm( forms.Form ) :
    url = forms.URLField( 
            required=True , 
            verify_exists=True ,
        )

django/g2c/converter/views.py
from django.http import HttpResponseRedirect
from django.template import loader 
from django.views.generic import simple as SimpleView

from g2c.converter.models import *

from g2c.converter import GreaseMonkeyConverter
from os import path


#loader.render_to_string ( String template_path , Dict context )
#simple.redirect_to
#simple.direct_to_template



def test( req ):
    return SimpleView.direct_to_template( req , "test/test.html" )


def convert( req ):
    form = ConverterForm( req.GET )
    result = form.is_valid()
    

    message = ""
    if result :
        try:
            target = GreaseMonkeyConverter.saveByURL( req.GET.get("url") )
            return HttpResponseRedirect( "/g2c/dl/" + path.dirname( target + "/" ).split( "/" )[-1] + ".crx" ) 
        except SyntaxError , ( msg ):
            result = False
            message = msg 



    return SimpleView.direct_to_template( req , "convert/result.html" , extra_context={ "result" : result , "form" : form , "message" : message } )

django/g2c/converter/templates/base.html
<!DOCTYPE HTML>
<html lang="jp">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock%}</title>
    {% block head %}{% endblock %}
    <link rel="stylesheet" href="/css/reset-fonts.css" type="text/css" />
<style type="text/css">
body { text-align:center; }
div#wrapper { width : 950px; margin : 0 auto 0 auto ; }
{% block css %}{% endblock %}</style>
</head>
<body>
    <div id="wrapper">
    <h1>{% block h1 %}{% endblock %}</h1>
    {% block body %}{% endblock %}
    </div>

    {% block enddoc %}{% endblock %}
</body>
</html>

django/g2c/converter/templates/convert/result.html
{% extends "base.html" %}
{% block title %}GreaseMonkey to Chrome extension Converter{% endblock %}
{% block css %}
.on  { display:block} .off { display:none }
#waitMessage { padding-top: 20px ; background : #FFF url( "/g2c/img/icon/load_bar.gif" ) no-repeat top center ; }
h1 { margin : 10px ; font-size : 2em ; } 
form { margin : 10px ; }
form #id_url {width:350px;}
{% endblock %}
{% block h1 %}GreaseMonkey to Chrome extension Converter{% endblock %}
{% block body %}
    <p>Input url of GreaseMonkey script to convert it to Chrome extension</p>
    {% if result %}
        success<br>
        You requested to convert {{form.url}}
    {% else %}
        <form onsubmit="onSubmit()" id="form" action="" method="GET">
            {{form.url}}
            <input type="submit" value="Convert" />
        </form>  
        <p id="waitMessage" class="off" >now converting..<br>please wait</p>
        <p class="errorMessage">{{message}}</p>
    {% endif %}
{% endblock %}
{% block enddoc %}
    <script type="text/javascript">
    function onSubmit (){
        document.getElementById( "form" ).className = "off" ;
        document.getElementById( "waitMessage" ).className = "on" ;
    }
    </script>
{% endblock %}

django/g2c/converter/templates/test.html
<!DOCTYPE HTML>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
test
	
</body>
</html>